### ISSUE TITLE
My procedure for compiling this (previously successful) no longer works I noticed today ...

### ISSUE THREAD

**Issue by nmvega** [Pulse-Eight/platform#10]
Hello friends:

I use (and compile) this 'Platform' component as part of building 'Kodi' extensions.

Up until today, the following sequence would compile this successfully:

# ===================================================
# BUILD PULSE-EIGHT PLATFORM ...
# ===================================================
cd /home/user/Downloads/KODI.d/CURRENT.d || exit 1
git clone https://github.com/Pulse-Eight/platform.git platform.d
cd /home/user/Downloads/KODI.d/CURRENT.d/platform.d || exit 1
cmake -DCMAKE_INSTALL_PREFIX=/opt/KODI.d
make
sudo make install
# ===================================================

But today, I unfortunately ran into the following compile error and don't know how to resolve it:

===========================================================
>> CMake Error at CMakeLists.txt:45 (install):
>>  install TARGETS given no ARCHIVE DESTINATION for static library target "platform".
>> -- Configuring incomplete, errors occurred!
>> See also ".../CMakeFiles/CMakeOutput.log".
>> See also ".../CMakeFiles/CMakeError.log".
>> make: *** No targets specified and no makefile found.  Stop.
============================================================

Do I need to tweak/augment the above compile steps? If so, can you provide guidance?

Thank you in advance! (I appreciate it).

**Comment by wsnipex** [comment]
please try https://github.com/Pulse-Eight/platform/pull/11
