### ISSUE TITLE
GPL-incompatible license is used for fstrcmp.c

### ISSUE THREAD

**Issue by rbalint** [Pulse-Eight/platform#12]
fstrcmp.c is covered by version 3.01 of the PHP license which is not compatible with GPL:
https://github.com/Pulse-Eight/platform/blob/master/src/util/fstrcmp.c
https://en.wikipedia.org/wiki/PHP_License

**Comment by opdenkamp** [comment]
@FernetMenta do you use this (still) for anything?

**Comment by FernetMenta** [comment]
I searched vnsi for fstrcmp: negative.

**Comment by opdenkamp** [comment]
heh, noticed that it may just have been you who committed it, not who actually used it ;)

**Comment by FernetMenta** [comment]
ahh, that is cmake sync. @wsnipex @akva2 do you know if this is used?

**Comment by akva2** [comment]
Yes it is used by the info scanners to do fuzzy steing compares.

**Comment by akva2** [comment]
Oh context lol. No it is not used here or on addons adaik.

**Comment by opdenkamp** [comment]
right, that would mean an easy solution to the problem then ;-)

**Comment by akva2** [comment]
Yes. The history of this is that i started moving xbmc/utils stuff into the platform library, then  have kodi use kodi-platform. One commit must have snuck into the wrong branch and has been carried onto here in the split. Issue is very much real in kodi itself though and there it will take more work..

-------- Opprinnelig melding --------
Fra: Lars Op den Kamp <notifications@github.com>
Dato: 26.11.2015 17:27 (GMT+01:00)
Til: Pulse-Eight/platform <platform@noreply.github.com>
Ko: Arne Morten Kvarving <Arne.Morten.Kvarving@sintef.no>
Emne: Re: [platform] GPL-incompatible license is used for fstrcmp.c (#12)


right, that would mean an easy solution to the problem then ;-)

**Comment by opdenkamp** [comment]
Sure, just mean that it's an easy solution _here_. As for the actual method, looks like a straight forward implementation of the described algo, so I'm not sure if the license actually is an issue here. I'll leave that up for debate later ;-)
