### ISSUE TITLE
fstrcmp() function and fstrcmp.h collide with libfstrcmp's well known symbol and header

### ISSUE THREAD

**Issue by rbalint** [Pulse-Eight/platform#13]
Platform embeds a very old version of the fstrcmp() function which is available in libfstrcmp for quite some time:
https://packages.qa.debian.org/f/fstrcmp.html
The local copy takes three parameters (where the last one is not used BTW)
```C
double fstrcmp (const char *__s1, const char *__s2, double __minimum);
```
versus the newer version in libfstrcmp which takes only two:
```C
double fstrcmp(const char *string1, const char *string2);
```
If any library or program dynamically links with libplatform _and_ libfstrcmp the C function name will be provided by both.

Please link to libfstrcmp instead of embedding the function or use the function internally but don't export it.

**Comment by opdenkamp** [comment]
same one as https://github.com/Pulse-Eight/platform/issues/12#issuecomment-159935699 @FernetMenta
