### ISSUE TITLE
Debian package unbuildable on Jessie due to Debian bug #700177

### ISSUE THREAD

**Issue by voltagex** [Pulse-Eight/platform#21]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=700177 means that a package version of `2.0.0-1~debian` isn't valid but `2.0.0.1~debian` is.

looks like only `debian/changelog.in` needs to be fixed but it affects your other repos too - do you want separate bugs?

**Comment by opdenkamp** [comment]
right, looks like I missed this one during the holidays. ubuntu seems to be fine with this version number, so I assume that this is some debian only policy?

version number `2.0.0.1~debian` isn't correct in my opinion, as it's lib version `2.0.0` with packaging version `1~debian`. the last part doesn't tell anything about the lib itself, just about how it's been packaged.

**Comment by wsnipex** [comment]
the difference is native vs quilt format. Native doesn't allow tag versions (-1)

**Comment by opdenkamp** [comment]
quilt is that thing that requires those incremental archives right? that's pretty much unusable for me

**Comment by opdenkamp** [comment]
I've changed the package version number to 3.1.0.1~#DIST#, even though I think that it's an odd policy to require it just to avoid potential confusion that one may think that it's been built differently. that's what `apt-get source` is for in my opinion.

**Comment by opdenkamp** [comment]
ah meh, forgot to push that, that was libCEC only, reopening for now :)
