### ISSUE TITLE
platform src build generates incorrect libdir entry in pkgconfig(p8-platform.pc)

### ISSUE THREAD

**Issue by pgnd** [Pulse-Eight/platform#24]
The comments at

    https://github.com/Pulse-Eight/libcec/issues/175

    opdenkamp commented 4 days ago

        it's the same bug as this one: Pulse-Eight/platform@51e2b28

        you need to update the platform lib to include this commit and I need to fix the same thing in libCEC

&

    opdenkamp commented 4 days ago

        set correctly here already, upgrading the platform lib should fix it
        https://github.com/Pulse-Eight/libcec/blob/master/cmake/PkgConfigHandler.cmake#L96

are unclear, as building latest platform pull still exhibits the pkg-config problem

What changes/fixes specifically need to be made here?

    cd cmake-platform
    git pull
    git log | head
        commit 38343e0acd6a636ac46139aa666aee4a8d1f13db
        Author: Lars Op den Kamp <lars@opdenkamp.eu>
        Date:   Tue Jan 19 20:49:33 2016 +0100

            bump to 2.0.1

        commit e1f8dc1b882069e52e6ead4380e3bb9b4792c398
        Merge: cce6a49 51e2b28
        Author: Lars Op den Kamp <opdenkamp@gmail.com>
        Date:   Mon Jan 18 20:55:13 2016 +0100

    cat CmakeLists.txt
        ...
        IF(NOT WIN32)
    ==>      configure_file(p8-platform.pc.in p8-platform.pc @ONLY)
          install(FILES ${CMAKE_BINARY_DIR}/p8-platform.pc
                  DESTINATION ${CMAKE_INSTALL_LIBDIR_NOARCH}/pkgconfig)
        ENDIF(NOT WIN32)
        ...

    mkdir build
    cd build
    cmake .. \
     -DCMAKE_INSTALL_PREFIX=/usr/local \
     -DBUILD_SHARED_LIBS=1 \
     -DCMAKE_INSTALL_LIBDIR=/usr/local/lib64 \
     -DCMAKE_INSTALL_LIBDIR_NOARCH=/usr/local/lib64

    make
    make install
        ...
        -- Installing: /usr/local/lib64/pkgconfig/p8-platform.pc
        ...

    cat  /usr/local/lib64/pkgconfig/p8-platform.pc
        prefix=/usr/local
    ???    libdir=/usr/local//usr/local/lib64
        includedir=/usr/local/include
        DEPENDENCIES=-lpthread

        Name: p8-platform
        Description: Pulse-Eight platform support library 2.0
        Version: 2.0.1
        Libs: -L${libdir} -lp8-platform
        Cflags: -I${includedir}

    pkg-config --libs p8-platform
    ???    -L/usr/local//usr/local/lib64 -lp8-platform

**Comment by opdenkamp** [comment]
https://github.com/Pulse-Eight/platform/pull/26 from @rbalint should fix your issue. It's just been merged and will be included in the next release
