### ISSUE TITLE
Packag conflict with libp8-platform2v4

### ISSUE THREAD

**Issue by ProfessorKaos64** [Pulse-Eight/platform#28]
If I build this myself and install it via clean room building (pbuilder) or a chroot, it conflicts with the Jessie backports package. Shound't the control fiend here specify to remove 2v4 since they conflict/replace each others files? Unfortunately pbuilder does not respect apt-pinning with the default setup. If this is not something that you deem reasonable, that is fine.

```
Selecting previously unselected package libp8-platform2:amd64.
(Reading database ... 54437 files and directories currently installed.)
Preparing to unpack .../libp8-platform2_2.0.1+git+bsos2_amd64.deb ...
Unpacking libp8-platform2:amd64 (2.0.1+git+bsos2) ...
dpkg: error processing archive /var/cache/apt/archives/libp8-platform2_2.0.1+git+bsos2_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libp8-platform.so.2.0.1', which is also in package libp8-platform2v4:amd64 2.0.1+dfsg1-1~bpo8+1
Selecting previously unselected package libp8-platform-dev:amd64.
Preparing to unpack .../libp8-platform-dev_2.0.1+git+bsos2_amd64.deb ...
Unpacking libp8-platform-dev:amd64 (2.0.1+git+bsos2) ...
Errors were encountered while processing:
 /var/cache/apt/archives/libp8-platform2_2.0.1+git+bsos2_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by opdenkamp** [comment]
This `2v4` is not a package that we released, but one that got forked by Debian maintainers, from this repos. Because they've renamed the name of the package for some reason, this will always conflict.

Please remove the package manually before installing this one.
