### ISSUE TITLE
cmake MultiArch libdir not set correctly

### ISSUE THREAD

**Issue by listsssl** [Pulse-Eight/platform#29]
I'm building 'platform'

    cd /home/lssl/source/platform
    git log | head
        commit 041a8c6cf4c44dbf0a8e295e3d3d2da13bbe0ad3
        Merge: 38343e0 d795fde
        Author: Lars Op den Kamp <opdenkamp@gmail.com>
        Date:   Sat Mar 19 20:54:21 2016 +0100

            Merge pull request #23 from Memphiz/no_iokit

            [tvos] - remove iokit linkage

        commit d795fde027981ae36abfcac85d7caf028d695cc4

According to

    https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html

        ...
        CMAKE_INSTALL_<dir>

            Destination for files of a given type. This value may be passed to the DESTINATION options of install() commands for the corresponding file type.
        ...
        LIBDIR
            object code libraries (lib or lib64 or lib/<multiarch-tuple> on Debian)
        ...

I should be able to specify

    -DCMAKE_INSTALL_LIBDIR=lib64
    -DCMAKE_INSTALL_LIBDIR_NOARCH=lib64

If I do

    cd build
    cmake\
     -DCMAKE_INSTALL_PREFIX=/usr/local \
     -DCMAKE_INSTALL_LIBDIR=lib64 \
     -DCMAKE_INSTALL_LIBDIR_NOARCH=lib64 \
    ..

the build generates this

    grep libdir= ./p8-platform.pc
        libdir=/usr/local//home/lssl/source/platform/build/lib64

instead of what you'd expect

    libdir=/usr/local/lib64

from

    grep libdir= p8-platform.pc.in
        libdir=@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_LIBDIR@

**Comment by listsssl** [comment]
I took a look at the cmake logic in CMakeLists.txt & UseMultiArch.cmake and can't make sense of it to fix it.

To get it all built correctly & installed in correct locations I can do this

    P="/usr/local"
    cmake\
     -DCMAKE_INSTALL_PREFIX=${P} \
     -DCMAKE_INSTALL_LIBDIR=${P}/lib64 \
     -DCMAKE_INSTALL_LIBDIR_NOARCH=${P}/lib64 \
    ..
    perl -pie 's|/usr/local//usr/local|/usr/local|g' ./p8-platform*
    make
    make install
    pkg-config --cflags --libs p8-platform
        -I/usr/local/include -L/usr/local/lib64 -lp8-platform
    grep /usr/local /usr/local/lib64/p8-platform/p8-platform-config.cmake
        set (p8-platform_INCLUDE_DIRS /usr/local/include/p8-platform /usr/local/include)
          set (p8-platform_LIBRARY "/usr/local/lib64/p8-platform.lib")
          set (p8-platform_LIBRARY "-L/usr/local/lib64 -lp8-platform")

**Comment by listsssl** [comment]
And to get libcec to build & install it's the same problem

    cd libcec/build
    cmake .. ...
    perl -pie 's|/usr/local//usr/local|/usr/local|g' ../src/libcec/libcec.pc
    make
    make install
    pkg-config --cflags --libs libcec
        -I/usr/local/include -I/usr/local/include/libcec -I/usr/local/include -L/usr/local/lib64 -lcec -lp8-platform
    ldd /usr/local/lib64/libcec.so.3.1.0 | grep p8
            libp8-platform.so.2.0 => /usr/local/lib64/libp8-platform.so.2.0 (0x00007f79694f3000)

**Comment by wsnipex** [comment]
GNUInstallDirs is not used in p8-platform nor libcec. A PR to use it instead of the homegrown multi-arch handling would most probably be welcome

**Comment by opdenkamp** [comment]
This PR by @rbalint fixes the wrong pkgconfig install dir: https://github.com/Pulse-Eight/platform/pull/26
