### ISSUE TITLE
In case of default config (/usr/local target) libplatform.a should go in /usr/local/lib

### ISSUE THREAD

**Issue by EricV2** [Pulse-Eight/platform#3]
multi-arch is for /usr only. Same fix has been made for kodi-platform. Actually it install in
ls -l /usr/local/lib/x86_64-linux-gnu/
total 156
-rw-r--r-- 1 root staff 157734 May  5 14:44 libplatform.a

But the linker only search for /usr/local/lib (dynamic and static) at elast ondebian and ubuntu

see https://github.com/xbmc/kodi-platform/commit/e022656e392b1ee56aab6719fd896f4b5f356651

**Comment by opdenkamp** [comment]
I'll sync the files

**Comment by opdenkamp** [comment]
https://github.com/Pulse-Eight/platform/commit/1890e2df1f13fe742bfe45d3f358dddc1b4ed9e9

**Comment by EricV2** [comment]
Thanks.
