### ISSUE TITLE
Are the Github access rights correct?

### ISSUE THREAD

**Issue by ovorel** [Pulse-Eight/platform#30]
Hello,
I am trying to fetch the platform repository with all the references, but receiving permission denied while fetching Pulse-Eight/libcec-support. Are the Github access rights setup correctly?
Thank you

`Initialized empty Git repository in /usr/portage/distfiles/git3-src/Pulse-Eight_platform.git/
 * Fetching https://github.com/Pulse-Eight/platform.git ...
git fetch https://github.com/Pulse-Eight/platform.git +refs/heads/master:refs/heads/master
remote: Counting objects: 500, done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 500 (delta 7), reused 0 (delta 0), pack-reused 475
Receiving objects: 100% (500/500), 177.13 KiB | 213.00 KiB/s, done.
Resolving deltas: 100% (280/280), done.
From https://github.com/Pulse-Eight/platform
 * [new branch]      master     -> master
 * [new tag]         p8-platform-2.1.0.1 -> p8-platform-2.1.0.1
 * [new tag]         1.0.0      -> 1.0.0
 * [new tag]         1.0.1      -> 1.0.1
 * [new tag]         1.0.10     -> 1.0.10
 * [new tag]         1.0.2      -> 1.0.2
 * [new tag]         1.0.3      -> 1.0.3
 * [new tag]         1.0.4      -> 1.0.4
 * [new tag]         1.0.5      -> 1.0.5
 * [new tag]         1.0.6      -> 1.0.6
 * [new tag]         1.0.7      -> 1.0.7
 * [new tag]         1.0.8      -> 1.0.8
 * [new tag]         1.0.9      -> 1.0.9
 * [new tag]         p8-platform-2.0.1 -> p8-platform-2.0.1
 * [new tag]         p8-platform-2.1.0 -> p8-platform-2.1.0
 * [new tag]         platform-2.1.0 -> platform-2.1.0
git symbolic-ref refs/git-r3/dev-libs/libp8-platform/0/__main__ refs/heads/master
Initialized empty Git repository in /usr/portage/distfiles/git3-src/git@github.com:Pulse-Eight_libcec-support.git/
 * Fetching git@github.com:Pulse-Eight/libcec-support.git ...
git fetch git@github.com:Pulse-Eight/libcec-support.git --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +HEAD:refs/git-r3/HEAD
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`

**Comment by pr3sidentspence** [comment]
+1

**Comment by Tryum** [comment]
The submodule referencing the support subgit is referreced by git/ssh while the other submodules of the libCEC project are referenced by https. It fails to clone this submodule if you don't have any ssh key registered to github.

**Comment by opdenkamp** [comment]
the PR from @Tryum that just got merged fixes this.
