### ISSUE TITLE
-DBUILD_SHARED_LIBS=1 should be default

### ISSUE THREAD

**Issue by EricV2** [Pulse-Eight/platform#5]
I wax wondering why I had only static libs, looked at the debian rules Makefile and found this define. IMHO, to be homogeneous with kodi where on Linux, shared libs are default (like kodi platform, pvr, ...) the default value should be to build shared libs

**Comment by opdenkamp** [comment]
This lib has nothing to do with Kodi's defaults, as it's not a part of Kodi. Kodi's PVR add-ons are using it though, and they all link this statically atm.

**Comment by EricV2** [comment]
I do not understand what you say: the debian makefile produce this lib as a shared lib so debian dependency will use shared libs. And libraries produced on Linux by default are shared libs so I do not get your point.

**Comment by opdenkamp** [comment]
yes that's debian, but that's not the default for anything else (e.g. windows)

**Comment by EricV2** [comment]
It should be default "On Linux".

**Comment by opdenkamp** [comment]
no, binary add-ons in kodi can't handle deps.

**Comment by EricV2** [comment]
What do you mean? If I try to build pvr-hts, I can't compile it without installing kodi-platform. If I install kodi-platform by default it produce a shared lib in /usr/local and include in /usr/local. And loading pvr-hts tries to load kodi-platform dynamic library (that's why installing in /usr/local/x86_64-linux-gnu was a mistake).

**Comment by opdenkamp** [comment]
not with add-ons that are shipped in a zip. and if you're on debian and building like that, then you can (but don't have to) use the dynamic lib and just use dpkg which sets it to dynamic. that doesn't mean that it has to be the default

**Comment by EricV2** [comment]
What I say is that by default on Linux (not using debian packaging), kodi platform, pvr-hts produce dynamic libraries on debian and that installing via "make install" install dynamic libraries (git  clone xxx, cd xxx, mkdir build, cmake .., make, sudo make install). I was wondering why this is different for this lib. That's all and I still think not homogeneous given the rest. Anyway I have updated my scripts but I have to make a special case for this libs (otherwyse I could do always the same sequence in a loop  for platform, kodi-platform and pvr-hts)

**Comment by opdenkamp** [comment]
because kodi's binary add-on system cannot handle dependencies, and link in this stuff statically by default.

**Comment by EricV2** [comment]
You just repeated what you said previously. I'm not producing zip file that do contain binary add-on nor does the default cmake file for this lib. I'm building from scratch using separate cmake build system that has been designed for binary addon.  Your library is currently the only one not build as a dynamic library (kodi-platform, pvr-hts) and building as a dynamic library fortunately works so I do not see why its is not default. That you need a flag to produce either static or dynamic libraries fine. That the default way of compiling and installing the package standalone on Linux is static, I still do not get. But I fail to convince you so I will shut up.
