### ISSUE TITLE
Platform name is very generic

### ISSUE THREAD

**Issue by rbalint** [Pulse-Eight/platform#9]
Hi,

I plan uploading the package to Debian with minor tweaks as a dependency for next libCEC version, but he name of the project - platform - is a bit too generic and the won't be accepted to Debian for sure. How about renaming the project or at least the Debian packages to libcec-platform or something similar?

Maybe the C++ namespace could be changed to something more specific as well.

Cheers,
Balint

**Comment by malard** [comment]
I am sure we can, however @opdenkamp is away until the end of the month and he is the maintainer of this project

**Comment by rbalint** [comment]
OK, I'll wait with updating libcec in Debian for him then, since I have to upload platfom/libcec-platform/? first.

**Comment by opdenkamp** [comment]
Hi, thanks for picking this up. I'm on holiday indeed, so will take a 
look at this later, but some remarks for now:
- namespace can't be changed as this lib is used by a dozen different 
libs and Kodi add-ons and has been in use for years with this name now. 
even if we wanted to change it, then we don't have control over all the 
other projects.
- as for the name `platform`, it's a proper name that describes what it 
is properly and this project is not part of libCEC (anymore), but is an 
abstraction that I wrote for the platform specific bits (linux, windows, 
bsd, android, etc.), which makes it a lot easier to write cross-platform 
code. So in my opinion this is a correct name for this lib.

**Comment by rbalint** [comment]
@opdenkamp I think it is a proper name from libCEC's and Kodi's POV, but if you consider that it will be part of a bigger ecosystem with many different libraries of tens of thousands of projects providing libraries abstracting different aspects of their supported platforms claiming ownership over the very generic name in the library namespace does not seem to be a good idea.
How about using the libpulseeight-platform or libkodi-platform name since the lib seems to be part of those ecosystems?
Ubuntu started using a similar name but they migrated away to libubuntu-* most probably for the reasons above:
https://launchpad.net/ubuntu/+source/platform-api

**Comment by opdenkamp** [comment]
There already is a kodi-platform too, which extends this lib :)

I'll see if I can come up with something else for the stuff in /debian, 
but I don't see this lib as something similar to the one you linked. 
That one actually is very much specific to Ubuntu's touch stuff, while 
our lib actually provides cross platform support for basic things like 
threads and mutexes.

**Comment by opdenkamp** [comment]
> I think it is a proper name from libCEC's and Kodi's POV

Kodi runs on about every platform (operating system) that matters 
nowadays, so Kodi's POV isn't that bad ;-)

**Comment by rbalint** [comment]
@opdenkamp From a quick glance libCEC could just depend on libkodiplatform and we are all set.
How about going that way?

**Comment by opdenkamp** [comment]
No, that would add a dep to tinyxml and stuff and be messy especially on windows.
Kodi-platform has a dep to libplatform, and so do libCEC and all of Kodi's binary add-ons.

**Comment by rbalint** [comment]
Yes I checked it further too, it would also introduce a dependency loop.
It is still strange that libkodiplatform ships  many fiies which are also shipped by platform derived from libcec.

**Comment by rbalint** [comment]
I bought up Ubuntu's stuff because they changed the name to something specific.
This project is similar to Apache Portable Runtime, which uses the "libapr" name instead of the very generic "libplatform" which is a very good practice.
https://apr.apache.org/docs/apr/1.5/modules.html

**Comment by rbalint** [comment]
For the initial packaging I'll go with libcec-platform and will rename the packages and the .so files if a better name is found.

**Comment by opdenkamp** [comment]
see https://github.com/Pulse-Eight/platform/pull/20
went for p8-platform as it's not just cec ;-)

**Comment by wsnipex** [comment]
@rbalint now that the lib has been renamed, please fix the naming mess you created. Your packages conflict with ours and are incompatible, which makes it a real pita to build in our ppa. I don't want to have to resort to epoch bumping games.
